### ISSUE TITLE
NoSuchMethod in Linux 3.13

### ISSUE THREAD

**Issue by dougreed** [oshi/oshi#822]
Recently upgraded from Version 3.5.0 to Version 3.13.0 (Also tried 3.12.2); Works in 3.5.0

Code snippets:
------------------------
private static       HardwareAbstractionLayer hal                = null;
private static       SystemInfo               systemInfo         = null;
...
systemInfo = new SystemInfo();
logger.debug("Operating System: {}", os.toString());
logger.debug("Family:           {}", family);
logger.debug("Manufacturer:     {}", manufacturer);
logger.debug("OS Version:       {}", osVersion);
...
hal            = systemInfo.getHardware();
GlobalMemory memory = hal.getMemory();
...

Output for system information:
----------------------------------------
Operating System: GNU/Linux Ubuntu 18.04.1 LTS (Bionic Beaver) build 4.15.0-38-generic
Family:           Ubuntu
Manufacturer:     GNU/Linux
OS Version:       18.04.1 LTS (Bionic Beaver) build 4.15.0-38-generic

When code reaches 'GlobalMemory memory = hal.getMemory();':
Exception in thread "PerformanceCollector" java.lang.NoSuchMethodError: com.sun.jna.Native.load(Ljava/lang/String;Ljava/lang/Class;)Lcom/sun/jna/Library;
	at com.sun.jna.platform.linux.LibC.<clinit>(LibC.java:43)
	at sun.misc.Unsafe.ensureClassInitialized(Native Method)
	at sun.reflect.UnsafeFieldAccessorFactory.newFieldAccessor(UnsafeFieldAccessorFactory.java:43)
	at sun.reflect.ReflectionFactory.newFieldAccessor(ReflectionFactory.java:156)
	at java.lang.reflect.Field.acquireFieldAccessor(Field.java:1088)
	at java.lang.reflect.Field.getFieldAccessor(Field.java:1069)
	at java.lang.reflect.Field.get(Field.java:393)
	at com.sun.jna.Native.loadLibraryInstance(Native.java:591)
	at com.sun.jna.Native.getLibraryOptions(Native.java:666)
	at com.sun.jna.Native.getStructureAlignment(Native.java:760)
	at com.sun.jna.Structure.setAlignType(Structure.java:269)
	at com.sun.jna.Structure.<init>(Structure.java:186)
	at com.sun.jna.Structure.<init>(Structure.java:182)
	at com.sun.jna.Structure.<init>(Structure.java:169)
	at com.sun.jna.Structure.<init>(Structure.java:161)
	at com.sun.jna.platform.linux.LibC$Sysinfo.<init>(LibC.java:47)
	at oshi.hardware.platform.linux.LinuxGlobalMemory.<init>(LinuxGlobalMemory.java:62)
	at oshi.hardware.platform.linux.LinuxHardwareAbstractionLayer.getMemory(LinuxHardwareAbstractionLayer.java:59)
	at cpssd.tools.SelfDiscover.getApplicationInstance(SelfDiscover.java:426)
	at cpssd.collector.PerformanceCollector.<clinit>(PerformanceCollector.java:82)

**Comment by dbwiddis** [comment]
Can you check your dependencies and ensure you have the latest JNA version?  Are you using OSGi bundle (see #752 -- needs update to JNA to fix)?

**Comment by dbwiddis** [comment]
Hi, @dougreed ... were you able to resolve this by updating to the latest OSHI and JNA versions?

**Comment by dougreed** [comment]
Sorry, No.  I didn’t (still don’t) know much about JNA, and was overly busy, so I just backed off at the time.  When I received this message, I updated to  to the most recent version through Maven, and tested. It still failed.  I assumed this meant I needed to go figure out where JNA is and install it.  I then did this, updated Maven, rebuilt, and retested.

It still failed in the same way.  Maybe I need to add some include file?  There is no error in the build.  I am most happy to help troubleshoot this if I can be of assistance, but I don’t know what to do.  It works on OSX, but fails on Linux.

Distributor ID:	LinuxMint
Description:	Linux Mint 18.2 Sonya
Release:	18.2
Codename:	sonya
Linux cp-master 4.8.0-53-generic #56~16.04.1-Ubuntu SMP Tue May 16 01:18:56 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux


            <dependency>
                <groupId>com.github.oshi</groupId>
                <artifactId>oshi-core</artifactId>
                <version>3.13.1</version>
            </dependency>
            <dependency>
                <groupId>net.java.dev.jna</groupId>
                <artifactId>jna</artifactId>
                <version>5.3.0</version>
            </dependency>


Exception in thread "SystemAnalyzer" java.lang.NoSuchMethodError: com.sun.jna.Native.load(Ljava/lang/String;Ljava/lang/Class;)Lcom/sun/jna/Library;
	at com.sun.jna.platform.linux.LibC.<clinit>(LibC.java:43)
	at sun.misc.Unsafe.ensureClassInitialized(Native Method)
	at sun.reflect.UnsafeFieldAccessorFactory.newFieldAccessor(UnsafeFieldAccessorFactory.java:43)
	at sun.reflect.ReflectionFactory.newFieldAccessor(ReflectionFactory.java:156)
	at java.lang.reflect.Field.acquireFieldAccessor(Field.java:1088)
	at java.lang.reflect.Field.getFieldAccessor(Field.java:1069)
	at java.lang.reflect.Field.get(Field.java:393)
	at com.sun.jna.Native.loadLibraryInstance(Native.java:591)
	at com.sun.jna.Native.getLibraryOptions(Native.java:666)
	at com.sun.jna.Native.getStructureAlignment(Native.java:760)
	at com.sun.jna.Structure.setAlignType(Structure.java:269)
	at com.sun.jna.Structure.<init>(Structure.java:186)
	at com.sun.jna.Structure.<init>(Structure.java:182)
	at com.sun.jna.Structure.<init>(Structure.java:169)
	at com.sun.jna.Structure.<init>(Structure.java:161)
	at com.sun.jna.platform.linux.LibC$Sysinfo.<init>(LibC.java:47)
	at oshi.hardware.platform.linux.LinuxGlobalMemory.<init>(LinuxGlobalMemory.java:62)
	at oshi.hardware.platform.linux.LinuxHardwareAbstractionLayer.getMemory(LinuxHardwareAbstractionLayer.java:59)
	at cpssd.tools.SelfDiscover.getApplicationInstance(SelfDiscover.java:426)
	at cpssd.SystemAnalyzer.<clinit>(SystemAnalyzer.java:83)




Douglas Reed
r.douglas.reed@gmail.com

**Comment by dbwiddis** [comment]
HI, @dougreed ... I think we were corresponding on this issue [here](https://github.com/oshi/oshi/issues/752#issuecomment-485562592).

I believe the source of your problem is not specifying the version in your child project POMs.  When a version isn't specified, the POM will accept any version in the repository, and if you haven't purged old versions, or old versions are downloaded as transitive dependencies for other libraries, it may just use those.

I'm confident you can fix this by specifying the version number in the child POM, either directly (OSHI 3.13.2 and JNA 5.3.1 are the latest versions) or by defining a property and referencing that property.
