### ISSUE TITLE
Release is broken: can't run mvn site

### ISSUE THREAD

**Issue by dbwiddis** [oshi/oshi#1702]
Well, JNA 5.9.0 came out so I attempted a release today and hit a new problem:
> [ERROR] Failed to execute goal org.apache.maven.plugins:maven-site-plugin:3.9.1:site (default-site) on project oshi-core: Error generating maven-javadoc-plugin:3.1.1:aggregate-no-fork report: 
> [ERROR] Exit code: 1 - /Users/danielwiddis/git/oshi/oshi-core/src/main/java/oshi/hardware/platform/mac/MacComputerSystem.java:31: error: package com.sun.jna does not exist
> [ERROR] import com.sun.jna.Native; 

This occurs during the `mvn site` step.  It looks like it may be a manifestation of https://issues.apache.org/jira/browse/MJAVADOC-609 which also points to https://issues.apache.org/jira/browse/MJAVADOC-620 as a root cause, but these were allegedly fixed in 3.2.0.

But I tried with 3.3.0 and the same issue.  I tried rolling back to the previous release state and the same issue.  I tried switching my java versions in case a recent change fixed it.  No help.  I am at a complete loss here.   @hazendaz do you have any idea what could be happening?  Any chance YOU can try to cut a release?

_Originally posted by @dbwiddis in https://github.com/oshi/oshi/issues/1145#issuecomment-903371231_

**Comment by dbwiddis** [comment]
OK, seems I can get it working by reverting to an earlier version of maven.  

It's working on 3.6.3 so I'll stick with that for now.  3.8.1 may work but haven't tried yet.

I can't be the only one seeing this, though... there seem to be quite a few issues with 3.8.2.
