### ISSUE TITLE
Upgrading to a new version of Slf4j for building the project using jlink/JPMS

### ISSUE THREAD

**Issue by all-creator** [oshi/oshi#1575]
I reopen the question about building the project using jlink, the fact is that the provided Java 11 version does work on build until a certain point, however it uses an outdated version of Slf4j that does not support JPMS, which is why the OSHI project is still does not support building via jlink, please update the Slf4j dependency to a version higher than 2.0. At least in the OSHI-java 11 branch, I hope this will be the last step in OSHI's transition to JPMS.

**Comment by dbwiddis** [comment]
From the SLF4J [download site](http://www.slf4j.org/download.html):
> The latest stable SLF4J is version 1.7.30.

This is the version OSHI depends on.  You are more than welcome to specify a newer version in your own POM; if you place it at a higher level in the dependency tree, it will take priority over the transitive dependency from OSHI.

Also from that site:
> SLF4J version 2.0.0-alpha1 is the most recent but it is also experimental/unstable.

I do not think it is a good idea for the "stable" OSHI library to depend on an "unstable" dependency.  

Per the [SLF4J FAQ](http://www.slf4j.org/faq.html#changesInVersion18), it is JPMS-compatible as of version 1.8.0.  However, there has not been a stable 1.8.0 release, so you would still have to rely on `1.8.0-beta4`.

I am willing to upgrade the version in the `java11` branch to the latest SLF4J 1.8.0-beta, but am reluctant to do so if it is not required. Again, I believe you have the ability to do this by specifying the slf4j version yourself in your own POM, which will override the transitive dependency from OSHI.  

You can also consider using the [ModiTect maven plugin](https://github.com/moditect/moditect) to add the module descriptor yourself, using the module descriptor from the [SLF4J source code](https://github.com/qos-ch/slf4j/blob/master/slf4j-api/src/main/java9/module-info.java).

**Comment by dbwiddis** [comment]
According to [this post](http://slf4j.42922.n3.nabble.com/Which-version-to-use-with-JPMS-td4027086.html) it seems safe to use the 1.8.0 beta.  I'll update the java11 branch for that in the next release.

But I still think you can use that version yourself. :)

**Comment by dbwiddis** [comment]
Or, [maybe 1.8.0 beta4 is not a good version to use](http://slf4j.42922.n3.nabble.com/slf4j-api-1-8-0-beta4-maven-javadoc-plugin-regression-when-jpms-is-enabled-td4027237.html).

**Comment by dbwiddis** [comment]
Based on [this site](https://blog.frankel.ch/update-state-java-modularization/) I might consider beta2.

But as you can see, without a stable release version, it's not obvious what the best choice is.  I really really think you can override this version yourself in your own POM so that OSHI doesn't have to. Please let me know if this is not possible, and why.

**Comment by hazendaz** [comment]
@dbwiddis 2 is stable using java 6 stuff so its not really modern.  1.8 is dead line and won't have more updates based on many comments I've seen over years.  Not clear why author isn't active at all regardless but 2.x is stable.  However, anyone using spring boot will be gravely affected.  2.x or 1.8.x will not be supported per spring policy of a real release.  All that said, it would be best to stick to 1.7.30 in this library.  Anyone can override it.  I run this with 2.x and have for years now.

**Comment by hazendaz** [comment]
note on spring boot: They hard wire into logback which is why it cannot be overridden.  slf4j 2 needs more recent logback that doesn't work in same way thus breaking spring boot.

**Comment by hazendaz** [comment]
I opened a ticket to try to get Ceki that owns slf4j to actually do something like release it.  Given its working into its second year and basically nothing on slf4j is active...would be nice that he just cuts it to get around this confusion.

**Comment by dbwiddis** [comment]
So basically the gist is:
 - It's best to stick to a stable release version in OSHI (I actually think one of our plugins stops me from releasing with beta dependencies) which means 1.7.30.
 - 2.0 is better (even alpha) than any of the 1.8.0, where it appears there was a regression from JPMS support back to non-support somewhere.
 - Users can easily specify a newer version in their top-level POM which will take precedence over OSHI's version loaded transitively, so no action is really required at the OSHI library level at this time.
 - It'd be great if 2.0 got released as stable if it really is and we can hope that happens.

**Comment by dbwiddis** [comment]
OK, I'll be cutting a release tonight and need to make a decision on whether to do anything here.  Here's my thoughts:
 - From a Java Module perspective, the only specification that matters is the `org.slf4j` module descriptor which has not changed
 - From an API perspective there is no difference in the code
 - Dependency version is entirely a maven thing and can be handled with by users' own POM files, adding top level dependencies or using transitive excludes, etc.
 - Users always need to add in their own implementations which should be of the same version as the API, so they should probably be overriding this anyway with their own matching versions of both
 - Jlink, et. al. can work without any reference to maven, so users can download appropriate jar files themselves

So it is not needed to upgrade the version.  However...
 - Making the change just reverses the default but still allows the user to override
 - The entire purpose of the java11 branch and maven artifacts is to enable modules
 - Using 1.7.x in that branch puts slf4j on the class path and not the module path.  It might be better to "default" to the module path

Given feedback in this issue that 2.0-alpha is "stable" I'll go ahead and update the java11 branch to use that dependency for now, keeping 1.7.x on the main project.  I don't think it really matters that much, but don't see a compelling reason not to.

**Comment by dbwiddis** [comment]
Fixed in 9ab9b4d2c4b2065b2650a350cced7cc354872980

**Comment by dbwiddis** [comment]
> ... don't see a compelling reason not to.

Well, now I do.  I've just wasted about 2 hours trying to troubleshoot why the java11 branch wouldn't release, chasing down some mysterious classloading failure for org.hamcrest.    

```
[ERROR] org.junit.platform.commons.JUnitException: TestEngine with ID 'junit-jupiter' failed to discover tests
[ERROR] Caused by: org.junit.platform.commons.JUnitException: ModuleSelector [moduleName = 'com.github.oshi'] resolution failed
[ERROR] Caused by: java.lang.NoClassDefFoundError: org/hamcrest/Matcher
[ERROR] Caused by: java.lang.ClassNotFoundException: org.hamcrest.Matcher
[ERROR] 	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:606)
[ERROR] 	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:168)
[ERROR] 	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
```

Finally did what I should have done at the start to isolate the offending commit to save time, and it's the change in slf4j version.  

I have no idea how to fix this, and I'm really done wasting time on JPMS.

Releasing with the old version.  Download the new jars if you want to use jlink.

**Comment by hazendaz** [comment]
junit 5 doesn't use hamcrest or any matcher directly anymore.  not sure if you upgraded to junit 5 but guessing not.  I would ditch any hamcrest and use assertj-core as the replacement and further make sure full junit 5 jupiter.

**Comment by dbwiddis** [comment]
I did upgrade to junit5 and separate hamcrest dependency.  See #1387.  

Why is assertj-core preferred over hamcrest? Why does any of this have to do with the version of slf4j?

**Comment by hazendaz** [comment]
assertj is just astronomically better, more broadly supported, and released frequently.  Plus its almost a verbatim replacement.  Hamcrest went defunct for a few years, low support.  It finally got new releases but by then junit separated its dependency leaving it free to decide.  I don't know the slf4j issue you noted, the output though noted issue with hamcrest.  It doesn't use slf4j.  Seems unrelated to me but I would at least replace hamcrest.  Hamcrest is already going on 2 years with no updates.  assertj on the other hand was last released in January of this year.

**Comment by dbwiddis** [comment]
Just as an FYI, I finally took the time to debug why the slf4j version caused issues.  

Short version is that having an slf4j version with a module descriptor put it on the module path, which required some extra configuraiton for testing, using `--add-modules` and `add-reads`.

So, after several months, as part of PR #1864 I'm doing what I attempted to do earlier for this issue:  leaving the main JDK8 project on a 1.x version, and using a 2.x (alpha) version for the modular release.  

Although I'm not sure how using the profile will impact downstream users as they'll read the 1.x version from the pom.  So maybe it doesn't matter.
