### ISSUE TITLE
Could not initialize class oshi.jna.platform.linux.Libc

### ISSUE THREAD

**Issue by lakstap** [oshi/oshi#338]
Caused by: java.lang.NoClassDefFoundError: Could not initialize class oshi.jna.platform.linux.Libc
        at oshi.hardware.platform.linux.LinuxCentralProcessor.getSystemLoadAverage(LinuxCentralProcessor.java:219)
        at oshi.json.hardware.impl.CentralProcessorImpl.getSystemLoadAverage(CentralProcessorImpl.java:238)

**Comment by dbwiddis** [comment]
Are you using the latest versions of both oshi-core and oshi-json?

**Comment by dbwiddis** [comment]
Hey @lakstap, I'd love to try to help resolve your issue.  My initial suspicion is that you have a mismatch of version numbers but I need more information on your setup to help you further.

**Comment by cpuchakayaka** [comment]
I have similar problem too, i am using oshi version 3.4.2

**Comment by dbwiddis** [comment]
It looks like this is probably related to updating JNA from 4.2.2 to 4.3.0 (with 4.4.0 planned for next release).  JNA now appears to require glibc version 2.14, but CentOS 6 has version 2.12.

See [here](https://github.com/java-native-access/jna/issues/771) and [here](https://github.com/elastic/elasticsearch/issues/23640) and [here](http://unix.stackexchange.com/questions/176489/how-to-update-glibc-to-2-14-in-centos-6-5).

Can you try an earlier version of OSHI (3.3) and see if the problem goes away?

**Comment by cpuchakayaka** [comment]
It works with 3.3, does it have similar issues with Centos 7 as well, as we have to have this working on it too

**Comment by dbwiddis** [comment]
My initial searching indicates CentOS 7 has glibc 2.17 and would therefore not have this issue.  I don't have a version of it on which to test so I'd advise you to confirm that yourself.

OSHI 3.4.0 still uses the earlier version of JNA and should be good for you to use.

**Comment by cpuchakayaka** [comment]
Ok cool, i will test it out, thanks :) 👍

**Comment by dbwiddis** [comment]
@lakstap are you by any chance also on CentOS 5 or 6?

**Comment by dbwiddis** [comment]
I'm inclined to close this issue because:
* It's being tracked in a JNA issue
* There's nothing I can do in OSHI (other than use an earlier version of JNA)
* There are workarounds (building JNA on the earlier CentOS)

Let me know if everything's working for you, @cpuchakayaka
